[build]
  command = "npm run build"
  publish = ".output/public" # Adjust to the output directory for your Nuxt app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"